language: node_js
node_js:
  - 14
services:
  - docker

before_install:
  - docker build -t cncs-web .
  - docker run -itd -p 127.0.0.1:80:3000 cncs-web
  - docker ps -a
  - docker run cncs-web yarn run test -watchAll=false

cache: yarn
