version: '3.7'

services:
  web:
    build: ./web
    command: yarn start
    volumes:
      - ./web/:/web/
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
        - ./web/:/web/
        - /web/node_modules
    env_file:
      - ./.env.local
    stdin_open: true
